/*
 * estoque.java
 *
 * Created on 15 de Julho de 2002, 10:54
 */

package br.com.conesteel.assest;

/**
 *
 * @author  Conesteel
 */
public class acabado extends javax.swing.JFrame {
    
    /** Creates new form estoque */
    public acabado() {
        initComponents();
        setSize(328,220);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        acabado = new javax.swing.JPanel();
        flanges = new javax.swing.JLabel();
        valvulas = new javax.swing.JLabel();
        conexoes = new javax.swing.JLabel();
        tubulares = new javax.swing.JLabel();
        barra_titulo = new javax.swing.JToolBar();
        titulo11 = new javax.swing.JLabel();
        estoque = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Assistente de Figuras");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        acabado.setLayout(null);

        acabado.setBackground(new java.awt.Color(255, 255, 255));
        flanges.setBackground(new java.awt.Color(255, 255, 255));
        flanges.setFont(new java.awt.Font("Arial", 1, 24));
        flanges.setForeground(java.awt.Color.blue);
        flanges.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        flanges.setText("Flanges");
        flanges.setToolTipText("");
        flanges.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClicou(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MouseSaiu(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MouseEntrou(evt);
            }
        });

        acabado.add(flanges);
        flanges.setBounds(10, 150, 310, 30);

        valvulas.setBackground(new java.awt.Color(255, 255, 255));
        valvulas.setFont(new java.awt.Font("Arial", 1, 24));
        valvulas.setForeground(java.awt.Color.blue);
        valvulas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        valvulas.setText("V\u00e1lvulas Compactas");
        valvulas.setToolTipText("");
        valvulas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClicou(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MouseSaiu(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MouseEntrou(evt);
            }
        });

        acabado.add(valvulas);
        valvulas.setBounds(10, 60, 310, 30);

        conexoes.setBackground(new java.awt.Color(255, 255, 255));
        conexoes.setFont(new java.awt.Font("Arial", 1, 24));
        conexoes.setForeground(java.awt.Color.blue);
        conexoes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        conexoes.setText("Conex\u00f5es Forjadas");
        conexoes.setToolTipText("");
        conexoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClicou(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MouseSaiu(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MouseEntrou(evt);
            }
        });

        acabado.add(conexoes);
        conexoes.setBounds(10, 90, 310, 30);

        tubulares.setBackground(new java.awt.Color(255, 255, 255));
        tubulares.setFont(new java.awt.Font("Arial", 1, 24));
        tubulares.setForeground(java.awt.Color.blue);
        tubulares.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tubulares.setText("Conex\u00f5es Tubulares");
        tubulares.setToolTipText("");
        tubulares.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClicou(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MouseSaiu(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MouseEntrou(evt);
            }
        });

        acabado.add(tubulares);
        tubulares.setBounds(10, 120, 310, 30);

        barra_titulo.setBackground(new java.awt.Color(0, 153, 255));
        barra_titulo.setFloatable(false);
        barra_titulo.setForeground(new java.awt.Color(51, 153, 255));
        titulo11.setForeground(new java.awt.Color(255, 255, 0));
        titulo11.setText("Escolha o Tipo do Estoque Acabado");
        barra_titulo.add(titulo11);

        acabado.add(barra_titulo);
        barra_titulo.setBounds(0, 0, 390, 20);

        estoque.setLayout(null);

        estoque.setBackground(new java.awt.Color(255, 255, 255));
        estoque.setBorder(new javax.swing.border.TitledBorder("Mudar o tipo do estoque"));
        jLabel1.setForeground(java.awt.Color.green);
        jLabel1.setText("ACABADO");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
        });

        estoque.add(jLabel1);
        jLabel1.setBounds(10, 20, 70, 16);

        acabado.add(estoque);
        estoque.setBounds(0, 20, 320, 40);

        getContentPane().add(acabado);
        acabado.setBounds(0, 0, 320, 190);

        pack();
    }//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        evt.getComponent().setForeground(java.awt.Color.red);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        evt.getComponent().setForeground(java.awt.Color.green);
    }//GEN-LAST:event_jLabel1MouseExited

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        evt.getComponent().setForeground(java.awt.Color.orange);
    }//GEN-LAST:event_jLabel1MouseEntered

    private void MouseSaiu(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MouseSaiu
        evt.getComponent().setForeground(java.awt.Color.blue);
    }//GEN-LAST:event_MouseSaiu

    private void MouseClicou(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MouseClicou
        evt.getComponent().setForeground(java.awt.Color.red);
    }//GEN-LAST:event_MouseClicou

    private void MouseEntrou(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MouseEntrou
        evt.getComponent().setForeground(java.awt.Color.orange);
    }//GEN-LAST:event_MouseEntrou

    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new acabado().show();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel valvulas;
    private javax.swing.JPanel estoque;
    private javax.swing.JLabel tubulares;
    private javax.swing.JLabel titulo11;
    private javax.swing.JToolBar barra_titulo;
    private javax.swing.JPanel acabado;
    private javax.swing.JLabel conexoes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel flanges;
    // End of variables declaration//GEN-END:variables

}
