/*
 * Ap1.java
 *
 * Created on 11 de Março de 2002, 20:24
 */
//import java.applet.* ;
//import ;

package TesteJava;

/**
 *
 * @author  Mauricio
 */
public class Ap1 extends java.applet.Applet {
    
    /** Initializes the applet Ap1 */
    public void init() {
        initComponents();
    }
    
    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        TXT_E = new java.awt.TextField();
        TXT_R = new java.awt.TextField();
        BT_R = new java.awt.Button();
        BT_E = new java.awt.Button();
        label1 = new java.awt.Label();
        label11 = new java.awt.Label();

        setLayout(null);

        add(TXT_E);
        TXT_E.setBounds(190, 30, 170, 20);

        add(TXT_R);
        TXT_R.setBounds(10, 30, 170, 20);

        BT_R.setLabel("Recebe");
        add(BT_R);
        BT_R.setBounds(240, 60, 59, 24);

        BT_E.setLabel("Envia");
        BT_E.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BT_EMouseClicked(evt);
            }
        });

        add(BT_E);
        BT_E.setBounds(60, 60, 46, 24);

        label1.setText("Vai receber");
        add(label1);
        label1.setBounds(190, 10, 66, 20);

        label11.setText("Vai enviar");
        add(label11);
        label11.setBounds(10, 10, 57, 20);

    }//GEN-END:initComponents

    private void BT_EMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_EMouseClicked
        java.applet.Applet cliente = null;
        cliente = getAppletContext().getApplet("CLIENTE");
        //cliente.Dados("AAA");
        //cliente.TXT_E.setText("AAA");
        //cliente
        ((Ap2)cliente).Dados("TESTE");
    }//GEN-LAST:event_BT_EMouseClicked
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label label1;
    private java.awt.Button BT_R;
    private java.awt.TextField TXT_R;
    private java.awt.Button BT_E;
    private java.awt.TextField TXT_E;
    private java.awt.Label label11;
    // End of variables declaration//GEN-END:variables

    
}
