/*
 * assvgav.java
 *
 * Created on 15 de Julho de 2002, 09:15
 */

package br.com.conesteel.assvgav;

/**
 *
 * @author  Conesteel
 */
public class assvgav extends javax.swing.JFrame {
    
    /** Creates new form assvgav */
    public assvgav() {
        initComponents();
        ArrumaTela("");
        setSize(408,310);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        Cabeçalho = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        castelo = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel211 = new javax.swing.JLabel();
        jLabel212 = new javax.swing.JLabel();
        jLabel213 = new javax.swing.JLabel();
        classe = new javax.swing.JPanel();
        jLabel2111 = new javax.swing.JLabel();
        jLabel2121 = new javax.swing.JLabel();
        passagem = new javax.swing.JPanel();
        jLabel2112 = new javax.swing.JLabel();
        jLabel2122 = new javax.swing.JLabel();
        extremidade = new javax.swing.JPanel();
        jLabel216 = new javax.swing.JLabel();
        jLabel2113 = new javax.swing.JLabel();
        jLabel2123 = new javax.swing.JLabel();
        jLabel2133 = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("V\u00e1lvula Gaveta Compacta Forjada");
        setLocationRelativeTo(getJMenuBar());
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        Cabeçalho.setLayout(null);

        Cabeçalho.setBorder(new javax.swing.border.BevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel1.setText("passagem");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        Cabeçalho.add(jLabel1);
        jLabel1.setBounds(210, 10, 60, 16);

        jLabel11.setText("castelo");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        Cabeçalho.add(jLabel11);
        jLabel11.setBounds(10, 10, 42, 16);

        jLabel12.setText("classe");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });

        Cabeçalho.add(jLabel12);
        jLabel12.setBounds(60, 10, 38, 16);

        jLabel13.setText("extremidade");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });

        Cabeçalho.add(jLabel13);
        jLabel13.setBounds(120, 10, 72, 16);

        getContentPane().add(Cabeçalho);
        Cabeçalho.setBounds(0, 0, 400, 80);

        castelo.setLayout(null);

        castelo.setBackground(new java.awt.Color(255, 255, 255));
        castelo.setBorder(new javax.swing.border.TitledBorder("Escolha o castelo"));
        jLabel21.setForeground(new java.awt.Color(0, 51, 204));
        jLabel21.setText("Castelo Soldado - Preme Porca Uni\u00e3o (IRRS)");
        castelo.add(jLabel21);
        jLabel21.setBounds(10, 80, 380, 16);

        jLabel211.setForeground(new java.awt.Color(0, 51, 204));
        jLabel211.setText("Castelo Aparafusado - Preme Aparafusado (OS&Y) (padr\u00e3o)");
        castelo.add(jLabel211);
        jLabel211.setBounds(10, 20, 380, 16);

        jLabel212.setForeground(new java.awt.Color(0, 51, 204));
        jLabel212.setText("Castelo Soldado - Preme Aparafusado");
        castelo.add(jLabel212);
        jLabel212.setBounds(10, 40, 380, 16);

        jLabel213.setForeground(new java.awt.Color(0, 51, 204));
        jLabel213.setText("Castelo Aparafusado - Preme Porca Uni\u00e3o (IRRS)");
        castelo.add(jLabel213);
        jLabel213.setBounds(10, 60, 380, 16);

        getContentPane().add(castelo);
        castelo.setBounds(0, 80, 400, 220);

        classe.setLayout(null);

        classe.setBackground(new java.awt.Color(255, 255, 255));
        classe.setBorder(new javax.swing.border.TitledBorder("Escolha a classe"));
        jLabel2111.setForeground(new java.awt.Color(0, 51, 204));
        jLabel2111.setText("800 PSI");
        classe.add(jLabel2111);
        jLabel2111.setBounds(10, 20, 380, 16);

        jLabel2121.setForeground(new java.awt.Color(0, 51, 204));
        jLabel2121.setText("1500 PSI");
        classe.add(jLabel2121);
        jLabel2121.setBounds(10, 40, 380, 16);

        getContentPane().add(classe);
        classe.setBounds(0, 80, 400, 220);

        passagem.setLayout(null);

        passagem.setBackground(new java.awt.Color(255, 255, 255));
        passagem.setBorder(new javax.swing.border.TitledBorder("Escolha a passagem"));
        jLabel2112.setForeground(new java.awt.Color(0, 51, 204));
        jLabel2112.setText("Passagem Reduzida (padr\u00e3o)");
        passagem.add(jLabel2112);
        jLabel2112.setBounds(10, 20, 380, 16);

        jLabel2122.setForeground(new java.awt.Color(0, 51, 204));
        jLabel2122.setText("Passagem Plena");
        passagem.add(jLabel2122);
        jLabel2122.setBounds(10, 40, 380, 16);

        getContentPane().add(passagem);
        passagem.setBounds(0, 80, 400, 220);

        extremidade.setLayout(null);

        extremidade.setBackground(new java.awt.Color(255, 255, 255));
        extremidade.setBorder(new javax.swing.border.TitledBorder("Escolha o extremidade"));
        jLabel216.setForeground(new java.awt.Color(0, 51, 204));
        jLabel216.setText("Encaixe para Solda (SW)");
        extremidade.add(jLabel216);
        jLabel216.setBounds(10, 80, 380, 16);

        jLabel2113.setForeground(new java.awt.Color(0, 51, 204));
        jLabel2113.setText("Rosca NPT");
        extremidade.add(jLabel2113);
        jLabel2113.setBounds(10, 20, 380, 16);

        jLabel2123.setForeground(new java.awt.Color(0, 51, 204));
        jLabel2123.setText("Rosca BSP");
        extremidade.add(jLabel2123);
        jLabel2123.setBounds(10, 40, 380, 16);

        jLabel2133.setForeground(new java.awt.Color(0, 51, 204));
        jLabel2133.setText("Rosca BSPT");
        extremidade.add(jLabel2133);
        jLabel2133.setBounds(10, 60, 380, 16);

        getContentPane().add(extremidade);
        extremidade.setBounds(0, 80, 400, 220);

        pack();
    }//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        ArrumaTela("passagem");
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        ArrumaTela("extremidade");
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        ArrumaTela("classe");
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        ArrumaTela("castelo");
    }//GEN-LAST:event_jLabel11MouseClicked
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new assvgav().show();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Cabeçalho;
    private javax.swing.JPanel extremidade;
    private javax.swing.JLabel jLabel216;
    private javax.swing.JPanel classe;
    private javax.swing.JLabel jLabel2123;
    private javax.swing.JLabel jLabel213;
    private javax.swing.JLabel jLabel2122;
    private javax.swing.JLabel jLabel212;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel2121;
    private javax.swing.JLabel jLabel211;
    private javax.swing.JPanel passagem;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2113;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2112;
    private javax.swing.JLabel jLabel2133;
    private javax.swing.JLabel jLabel2111;
    private javax.swing.JPanel castelo;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    
    private void ArrumaTela(String Tipo) {
        castelo.hide();
        extremidade.hide();
        passagem.hide();
        classe.hide();
        if( Tipo.equalsIgnoreCase("castelo") || Tipo.equalsIgnoreCase("") )
        {
            castelo.show();
        }
        if( Tipo.equalsIgnoreCase("extremidade") )
        {
            extremidade.show();
        }
        if( Tipo.equalsIgnoreCase("passagem") )
        {
            passagem.show();
        }
        if( Tipo.equalsIgnoreCase("classe") )
        {
            classe.show();
        }
    }
}
