/*
 * estoque.java
 *
 * Created on 15 de Julho de 2002, 10:54
 */

package br.com.conesteel.assest;

/**
 *
 * @author  Conesteel
 */
public class estoque extends javax.swing.JFrame {
    
    /** Creates new form estoque */
    public estoque() {
        initComponents();
        setSize(330,190);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        estoque = new javax.swing.JPanel();
        acabado = new javax.swing.JLabel();
        bruto = new javax.swing.JLabel();
        andamento = new javax.swing.JLabel();
        componente = new javax.swing.JLabel();
        barra_titulo = new javax.swing.JToolBar();
        titulo = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Assistente de Figuras");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        estoque.setLayout(null);

        estoque.setBackground(new java.awt.Color(255, 255, 255));
        acabado.setBackground(new java.awt.Color(255, 255, 255));
        acabado.setFont(new java.awt.Font("Arial", 1, 24));
        acabado.setForeground(java.awt.Color.blue);
        acabado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acabado.setText("Acabado");
        acabado.setToolTipText("");
        acabado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClicou(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MouseSaiu(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MouseEntrou(evt);
            }
        });

        estoque.add(acabado);
        acabado.setBounds(10, 120, 310, 30);

        bruto.setBackground(new java.awt.Color(255, 255, 255));
        bruto.setFont(new java.awt.Font("Arial", 1, 24));
        bruto.setForeground(java.awt.Color.blue);
        bruto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bruto.setText("Bruto");
        bruto.setToolTipText("");
        bruto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClicou(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MouseSaiu(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MouseEntrou(evt);
            }
        });

        estoque.add(bruto);
        bruto.setBounds(10, 30, 310, 30);

        andamento.setBackground(new java.awt.Color(255, 255, 255));
        andamento.setFont(new java.awt.Font("Arial", 1, 24));
        andamento.setForeground(java.awt.Color.blue);
        andamento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        andamento.setText("Produ\u00e7\u00e3o em Andamento");
        andamento.setToolTipText("");
        andamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClicou(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MouseSaiu(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MouseEntrou(evt);
            }
        });

        estoque.add(andamento);
        andamento.setBounds(10, 60, 310, 30);

        componente.setBackground(new java.awt.Color(255, 255, 255));
        componente.setFont(new java.awt.Font("Arial", 1, 24));
        componente.setForeground(java.awt.Color.blue);
        componente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        componente.setText("Componentes");
        componente.setToolTipText("");
        componente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClicou(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MouseSaiu(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MouseEntrou(evt);
            }
        });

        estoque.add(componente);
        componente.setBounds(10, 90, 310, 30);

        barra_titulo.setBackground(new java.awt.Color(0, 153, 255));
        barra_titulo.setFloatable(false);
        barra_titulo.setForeground(new java.awt.Color(51, 153, 255));
        titulo.setForeground(new java.awt.Color(255, 255, 0));
        titulo.setText("Escolha o Tipo do Estoque");
        barra_titulo.add(titulo);

        estoque.add(barra_titulo);
        barra_titulo.setBounds(0, 0, 390, 20);

        getContentPane().add(estoque);
        estoque.setBounds(0, 0, 330, 160);

        pack();
    }//GEN-END:initComponents

    private void MouseSaiu(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MouseSaiu
        evt.getComponent().setForeground(java.awt.Color.blue);
    }//GEN-LAST:event_MouseSaiu

    private void MouseClicou(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MouseClicou
        evt.getComponent().setForeground(java.awt.Color.red);
    }//GEN-LAST:event_MouseClicou

    private void MouseEntrou(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MouseEntrou
        evt.getComponent().setForeground(java.awt.Color.orange);
    }//GEN-LAST:event_MouseEntrou

    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new estoque().show();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel titulo;
    private javax.swing.JPanel estoque;
    private javax.swing.JLabel andamento;
    private javax.swing.JLabel bruto;
    private javax.swing.JToolBar barra_titulo;
    private javax.swing.JLabel acabado;
    private javax.swing.JLabel componente;
    // End of variables declaration//GEN-END:variables

}
