/*
 * estoque.java
 *
 * Created on 15 de Julho de 2002, 10:54
 */

package br.com.conesteel.assest.produtos;

/**
 *
 * @author  Conesteel
 */
public class gaveta extends javax.swing.JFrame {
    
    /** Creates new form estoque */
    public gaveta() {
        initComponents();
        setSize(338,250);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        valvulas = new javax.swing.JPanel();
        tarugo = new javax.swing.JLabel();
        barra_titulo = new javax.swing.JToolBar();
        titulo = new javax.swing.JLabel();
        acabado = new javax.swing.JPanel();
        tipo_acabado = new javax.swing.JLabel();
        estoque = new javax.swing.JPanel();
        tipo_estoque = new javax.swing.JLabel();
        acabado1 = new javax.swing.JPanel();
        tipo_acabado1 = new javax.swing.JLabel();
        estoque1 = new javax.swing.JPanel();
        tipo_estoque1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel111 = new javax.swing.JLabel();
        jLabel1111 = new javax.swing.JLabel();
        jLabel11111 = new javax.swing.JLabel();
        jLabel11112 = new javax.swing.JLabel();
        jLabel11113 = new javax.swing.JLabel();
        jLabel11114 = new javax.swing.JLabel();
        jLabel111111 = new javax.swing.JLabel();
        estoque2 = new javax.swing.JPanel();
        tipo_estoque2 = new javax.swing.JLabel();
        jLabel111112 = new javax.swing.JLabel();
        jLabel1111121 = new javax.swing.JLabel();
        jLabel1111122 = new javax.swing.JLabel();
        jLabel1111123 = new javax.swing.JLabel();
        jLabel1111124 = new javax.swing.JLabel();
        jLabel1111125 = new javax.swing.JLabel();
        jLabel1111126 = new javax.swing.JLabel();
        jLabel1111127 = new javax.swing.JLabel();
        jLabel1111128 = new javax.swing.JLabel();
        jLabel1111129 = new javax.swing.JLabel();
        jLabel11111210 = new javax.swing.JLabel();
        jLabel11111211 = new javax.swing.JLabel();
        jLabel11111212 = new javax.swing.JLabel();
        jLabel11111213 = new javax.swing.JLabel();
        jLabel11111215 = new javax.swing.JLabel();
        jLabel111112121 = new javax.swing.JLabel();
        jLabel11111261 = new javax.swing.JLabel();
        jLabel11111262 = new javax.swing.JLabel();
        jLabel11111263 = new javax.swing.JLabel();
        jLabel11111264 = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Assistente de Figuras");
        setIconImage(getIconImage());
        setLocationRelativeTo(this);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        valvulas.setLayout(null);

        valvulas.setBackground(new java.awt.Color(255, 255, 255));
        tarugo.setBackground(new java.awt.Color(255, 255, 255));
        tarugo.setFont(new java.awt.Font("Arial", 1, 24));
        tarugo.setForeground(java.awt.Color.blue);
        tarugo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tarugo.setText("Tarugo - Ponta de Agulha");
        tarugo.setToolTipText("");
        tarugo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClicou(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MouseSaiu(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MouseEntrou(evt);
            }
        });

        valvulas.add(tarugo);
        tarugo.setBounds(20, 350, 310, 30);

        barra_titulo.setBackground(new java.awt.Color(0, 153, 255));
        barra_titulo.setFloatable(false);
        barra_titulo.setForeground(new java.awt.Color(51, 153, 255));
        titulo.setForeground(new java.awt.Color(255, 255, 0));
        titulo.setText("Escolha o Tipo de V\u00e1lvula Gaveta");
        barra_titulo.add(titulo);

        valvulas.add(barra_titulo);
        barra_titulo.setBounds(0, 0, 390, 20);

        acabado.setLayout(null);

        acabado.setBackground(new java.awt.Color(255, 255, 255));
        acabado.setBorder(new javax.swing.border.TitledBorder(null, "Mudar o tipo do Acabado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 10)));
        tipo_acabado.setForeground(java.awt.Color.green);
        tipo_acabado.setText("V\u00c1LVULA COMPACTA");
        tipo_acabado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EstoqueClicou(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EstoqueSaiu(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EstoqueEntrou(evt);
            }
        });

        acabado.add(tipo_acabado);
        tipo_acabado.setBounds(10, 20, 140, 16);

        valvulas.add(acabado);
        acabado.setBounds(170, 20, 160, 40);

        estoque.setLayout(null);

        estoque.setBackground(new java.awt.Color(255, 255, 255));
        estoque.setBorder(new javax.swing.border.TitledBorder(null, "Mudar o tipo do Estoque", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 10)));
        tipo_estoque.setForeground(java.awt.Color.green);
        tipo_estoque.setText("ACABADO");
        tipo_estoque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EstoqueClicou(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EstoqueSaiu(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EstoqueEntrou(evt);
            }
        });

        estoque.add(tipo_estoque);
        tipo_estoque.setBounds(10, 20, 70, 16);

        valvulas.add(estoque);
        estoque.setBounds(0, 20, 160, 40);

        acabado1.setLayout(null);

        acabado1.setBackground(new java.awt.Color(255, 255, 255));
        acabado1.setBorder(new javax.swing.border.TitledBorder(null, "Mudar o tipo do Acabado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 10)));
        tipo_acabado1.setForeground(java.awt.Color.green);
        tipo_acabado1.setText("V\u00c1LVULA COMPACTA");
        acabado1.add(tipo_acabado1);
        tipo_acabado1.setBounds(10, 20, 140, 16);

        valvulas.add(acabado1);
        acabado1.setBounds(340, 20, 160, 40);

        estoque1.setLayout(null);

        estoque1.setBackground(new java.awt.Color(255, 255, 255));
        estoque1.setBorder(new javax.swing.border.TitledBorder(null, "Detalhes da V\u00e1lvula Gaveta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 10)));
        tipo_estoque1.setForeground(java.awt.Color.green);
        tipo_estoque1.setText("ACABADO");
        estoque1.add(tipo_estoque1);
        tipo_estoque1.setBounds(100, 20, 70, 16);

        jLabel12.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel12.setText("Configura\u00e7\u00e3o:");
        estoque1.add(jLabel12);
        jLabel12.setBounds(10, 20, 80, 15);

        jLabel111.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel111.setText("Extremidade:");
        estoque1.add(jLabel111);
        jLabel111.setBounds(10, 60, 80, 15);

        jLabel1111.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel1111.setText("Bitola:");
        estoque1.add(jLabel1111);
        jLabel1111.setBounds(310, 80, 80, 15);

        jLabel11111.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel11111.setText("Tipo:");
        estoque1.add(jLabel11111);
        jLabel11111.setBounds(10, 40, 80, 15);

        jLabel11112.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel11112.setText("Classe:");
        estoque1.add(jLabel11112);
        jLabel11112.setBounds(310, 20, 80, 15);

        jLabel11113.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel11113.setText("Internos:");
        estoque1.add(jLabel11113);
        jLabel11113.setBounds(310, 40, 80, 15);

        jLabel11114.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel11114.setText("Material:");
        estoque1.add(jLabel11114);
        jLabel11114.setBounds(310, 60, 80, 15);

        jLabel111111.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel111111.setText("Passagem:");
        estoque1.add(jLabel111111);
        jLabel111111.setBounds(10, 80, 80, 15);

        estoque2.setLayout(null);

        estoque2.setBackground(new java.awt.Color(255, 255, 255));
        estoque2.setBorder(new javax.swing.border.TitledBorder(null, "Personalizar a configura\u00e7\u00e3o de material da v\u00e1lvula:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 10)));
        tipo_estoque2.setForeground(java.awt.Color.green);
        tipo_estoque2.setText("A-182 F304L");
        estoque2.add(tipo_estoque2);
        tipo_estoque2.setBounds(60, 20, 70, 16);

        jLabel111112.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel111112.setText("Haste:");
        estoque2.add(jLabel111112);
        jLabel111112.setBounds(130, 60, 120, 15);

        jLabel1111121.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel1111121.setText("Corpo:");
        estoque2.add(jLabel1111121);
        jLabel1111121.setBounds(10, 20, 80, 15);

        jLabel1111122.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel1111122.setText("Castelo:");
        estoque2.add(jLabel1111122);
        jLabel1111122.setBounds(10, 40, 80, 15);

        jLabel1111123.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel1111123.setText("Preme:");
        estoque2.add(jLabel1111123);
        jLabel1111123.setBounds(10, 60, 80, 15);

        jLabel1111124.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel1111124.setText("Cunha:");
        estoque2.add(jLabel1111124);
        jLabel1111124.setBounds(10, 80, 80, 15);

        jLabel1111125.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel1111125.setText("An\u00e9is:");
        estoque2.add(jLabel1111125);
        jLabel1111125.setBounds(130, 40, 80, 15);

        jLabel1111126.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel1111126.setText("Pontas:");
        estoque2.add(jLabel1111126);
        jLabel1111126.setBounds(370, 120, 100, 15);

        jLabel1111127.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel1111127.setText("Volante:");
        estoque2.add(jLabel1111127);
        jLabel1111127.setBounds(190, 80, 80, 15);

        jLabel1111128.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel1111128.setText("Gaxeta:");
        estoque2.add(jLabel1111128);
        jLabel1111128.setBounds(190, 60, 80, 15);

        jLabel1111129.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel1111129.setText("Prisioneiro Corpo:");
        estoque2.add(jLabel1111129);
        jLabel1111129.setBounds(320, 20, 110, 15);

        jLabel11111210.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel11111210.setText("Porca Corpo:");
        estoque2.add(jLabel11111210);
        jLabel11111210.setBounds(320, 40, 80, 15);

        jLabel11111211.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel11111211.setText("Prisioneiro Preme:");
        estoque2.add(jLabel11111211);
        jLabel11111211.setBounds(320, 60, 120, 15);

        jLabel11111212.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel11111212.setText("Placa de Identifica\u00e7\u00e3o:");
        estoque2.add(jLabel11111212);
        jLabel11111212.setBounds(320, 100, 130, 15);

        jLabel11111213.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel11111213.setText("Junta:");
        estoque2.add(jLabel11111213);
        jLabel11111213.setBounds(190, 40, 120, 15);

        jLabel11111215.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel11111215.setText("Bucha Movimento:");
        estoque2.add(jLabel11111215);
        jLabel11111215.setBounds(190, 20, 120, 15);

        jLabel111112121.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel111112121.setText("Porca Preme:");
        estoque2.add(jLabel111112121);
        jLabel111112121.setBounds(320, 80, 120, 15);

        jLabel11111261.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel11111261.setText("Porca Volante:");
        estoque2.add(jLabel11111261);
        jLabel11111261.setBounds(190, 100, 100, 15);

        jLabel11111262.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel11111262.setText("Revestimento:");
        estoque2.add(jLabel11111262);
        jLabel11111262.setBounds(90, 120, 100, 15);

        jLabel11111263.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel11111263.setText("Solda Adapta\u00e7\u00e3o:");
        estoque2.add(jLabel11111263);
        jLabel11111263.setBounds(180, 120, 100, 15);

        jLabel11111264.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel11111264.setText("Flanges:");
        estoque2.add(jLabel11111264);
        jLabel11111264.setBounds(290, 120, 100, 15);

        estoque1.add(estoque2);
        estoque2.setBounds(10, 100, 530, 150);

        valvulas.add(estoque1);
        estoque1.setBounds(0, 70, 560, 270);

        getContentPane().add(valvulas);
        valvulas.setBounds(0, 0, 610, 380);

        pack();
    }//GEN-END:initComponents

    private void EstoqueClicou(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EstoqueClicou
        evt.getComponent().setForeground(java.awt.Color.red);
    }//GEN-LAST:event_EstoqueClicou

    private void EstoqueSaiu(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EstoqueSaiu
        evt.getComponent().setForeground(java.awt.Color.green);
    }//GEN-LAST:event_EstoqueSaiu

    private void EstoqueEntrou(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EstoqueEntrou
        evt.getComponent().setForeground(java.awt.Color.orange);
    }//GEN-LAST:event_EstoqueEntrou

    private void MouseSaiu(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MouseSaiu
        evt.getComponent().setForeground(java.awt.Color.blue);
    }//GEN-LAST:event_MouseSaiu

    private void MouseClicou(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MouseClicou
        evt.getComponent().setForeground(java.awt.Color.red);
    }//GEN-LAST:event_MouseClicou

    private void MouseEntrou(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MouseEntrou
        evt.getComponent().setForeground(java.awt.Color.orange);
    }//GEN-LAST:event_MouseEntrou
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new gaveta().show();
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel tipo_acabado;
    private javax.swing.JPanel valvulas;
    private javax.swing.JPanel estoque2;
    private javax.swing.JPanel estoque1;
    private javax.swing.JLabel titulo;
    private javax.swing.JPanel estoque;
    private javax.swing.JLabel tipo_acabado1;
    private javax.swing.JLabel jLabel11111215;
    private javax.swing.JLabel jLabel11111213;
    private javax.swing.JLabel tipo_estoque;
    private javax.swing.JLabel jLabel11111212;
    private javax.swing.JLabel jLabel11111211;
    private javax.swing.JLabel jLabel11111210;
    private javax.swing.JLabel jLabel1111;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel tipo_estoque2;
    private javax.swing.JLabel tipo_estoque1;
    private javax.swing.JLabel tarugo;
    private javax.swing.JToolBar barra_titulo;
    private javax.swing.JLabel jLabel1111129;
    private javax.swing.JLabel jLabel1111128;
    private javax.swing.JLabel jLabel1111127;
    private javax.swing.JLabel jLabel1111126;
    private javax.swing.JLabel jLabel111112;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel1111125;
    private javax.swing.JLabel jLabel111111;
    private javax.swing.JLabel jLabel11114;
    private javax.swing.JLabel jLabel11111264;
    private javax.swing.JLabel jLabel1111124;
    private javax.swing.JLabel jLabel11113;
    private javax.swing.JPanel acabado;
    private javax.swing.JLabel jLabel11111263;
    private javax.swing.JLabel jLabel1111123;
    private javax.swing.JLabel jLabel11112;
    private javax.swing.JPanel acabado1;
    private javax.swing.JLabel jLabel11111262;
    private javax.swing.JLabel jLabel1111122;
    private javax.swing.JLabel jLabel11111;
    private javax.swing.JLabel jLabel11111261;
    private javax.swing.JLabel jLabel1111121;
    private javax.swing.JLabel jLabel111112121;
    // End of variables declaration//GEN-END:variables

}
