package XUXU;

/*
 * TestePrint.java
 *
 * Created on 21 de Março de 2002, 19:43
 */

/**
 *
 * @author  Mauricio
 */
import XUXU.*;

public class TestePrint extends java.applet.Applet {
    
    /** Initializes the applet TestePrint */
    public void init() {
        initComponents();
        
        //XUXU.Formulario xxx = new Formulario();
    }
    
    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jFrame1 = new javax.swing.JFrame();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jOptionPane1 = new javax.swing.JOptionPane();
        jDialog1 = new javax.swing.JDialog();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setLayout(null);

        jButton1.setText("jButton1");
        add(jButton1);
        jButton1.setBounds(30, 110, 81, 26);

        jTextField1.setText("jTextField1");
        add(jTextField1);
        jTextField1.setBounds(30, 20, 63, 20);

    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JOptionPane jOptionPane1;
    // End of variables declaration//GEN-END:variables
        
}
