/*
 * Teste2.java
 *
 * Created on 21 de Abril de 2002, 17:05
 */

/**
 *
 * @author  Mauricio
 */
//package siscoval;

import java.net.*;

public class Teste2 extends javax.swing.JApplet {
    
    /** Creates new form Teste2 */
    public Teste2() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jButton1 = new javax.swing.JButton();

        getContentPane().setLayout(null);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        getContentPane().add(jButton1);
        jButton1.setBounds(70, 60, 260, 180);

    }//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try
        {
            URL u = new URL("javascript:window.open('http://www.google.com.br','Scv','height=118,width=500,resizable=no,screenX=0,screenY=0,status=no,toolbar=no,scrolbars=no,titlebar=no,menubar=no');window.close()");
            
            this.getAppletContext().showDocument(u,"_blank");
        }
        catch(MalformedURLException e)
        {
            this.showStatus("deu pau");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
    public String XUXU() {
        return "XUXU";
    }
    
}
