/*
 * Teste1.java
 *
 * Created on 21 de Abril de 2002, 17:05
 */

/**
 *
 * @author  Mauricio
 */
//package siscoval;

public class Teste1 extends javax.swing.JApplet {
    
    /** Creates new form Teste1 */
    public Teste1() {
        initComponents();
        
        
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jList1 = new javax.swing.JList();

        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jTextField1.setText("jTextField1");
        jPanel1.add(jTextField1);
        jTextField1.setBounds(160, 230, 350, 20);

        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(160, 210, 41, 16);

        jTextField11.setText("jTextField1");
        jPanel1.add(jTextField11);
        jTextField11.setBounds(160, 80, 350, 20);

        jLabel11.setText("jLabel1");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(160, 60, 41, 16);

        jTextField12.setText("jTextField1");
        jPanel1.add(jTextField12);
        jTextField12.setBounds(160, 130, 350, 20);

        jLabel12.setText("jLabel1");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(160, 110, 41, 16);

        jTextField13.setText("jTextField1");
        jPanel1.add(jTextField13);
        jTextField13.setBounds(160, 180, 350, 20);

        jLabel13.setText("jLabel1");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(160, 160, 41, 16);

        jPanel2.setLayout(null);

        jPanel2.setBorder(new javax.swing.border.EtchedBorder());
        jPanel2.add(jList1);
        jList1.setBounds(10, 10, 110, 180);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 40, 130, 200);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 580, 360);

    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JList jList1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
